#!/bin/sh

error () {
    echo $* 1>&2
}

# check for migrations subdirectory in current directory
if [ ! -d "migrations" ]; then
    error "ERROR: Directory 'migrations' not found.\nDid you initialize migrations for this project?"
    exit 1
fi

# check for configuration file named 'config' in migrations directory
if [ ! -f "migrations/config" ]; then
    error "ERROR: Configuration 'migrations/config' not found."
    error "Please add the configuration file named 'config' to the migrations directory"
    exit 1
fi

# TODO: hmm, is there a better way to read configs in bash? when there is
# something wrong in the config file (syntax error perhaps) that can lead to
# the migrate script crashing...
. migrations/config

# check for required configuration settings
if [ -z "$db_host" ]; then
    error "ERROR: Missing required configuration setting 'db_host' in 'migrations/config'."
    error "Please specify the hostname migrate should connect to in the config file"
    exit 1
fi
if [ -z "$db_user" ]; then
    error "ERROR: Missing required configuration setting 'db_user' in 'migrations/config'."
    error "Please specify the user migrate should use to connect to the database in the config file"
    exit 1
fi
if [ -z "$db_password" ]; then
    error "ERROR: Missing required configuration setting 'db_password' in 'migrations/config'."
    error "Please specify the password migrate should use to connect to the database in the config file"
    exit 1
fi
if [ -z "$db_name" ]; then
    error "ERROR: Missing required configuration setting 'db_name' in 'migrations/config'."
    error "Please specify the database name migrate should connect to in the config file"
    exit 1
fi

for f in migrations/*; do
    if echo $f | grep "^migrations/.*\.sql$" >/dev/null; then
        mysql_out=$(mysql --host="$db_host" --user="$db_user" --password="$db_password" --database="$db_name" < $f 2>&1)
        if [ $? != 0 ]; then
            # attempt to convert the errors given by MySQL to errors which
            # provide the user context
            if echo $mysql_out | grep "^ERROR 2005 (HY000): Unknown MySQL server host '$db_host' (0)$" >/dev/null; then
                error "ERROR: Cannot connect to host '$db_host'."
                error "Is the host specified in the configuration file up and reachable?"
            elif echo $mysql_out | grep "^ERROR 1045 (28000): Access denied for user '$db_user'@'$db_host' (using password: NO)" >/dev/null; then
                error "ERROR: Access denied for database user '$db_user'."
                error "Is the username '$db_user' specified in the configuration correct?"
            else
                error "ERROR: the database returned the following error:"
                error $mysql_out
            fi
            exit 1
        fi
    fi
done

echo "Migrate ran successfully."
echo "However there were no migrations executed as none were found in the migrations directory"
exit 0
